### ISSUE TITLE
Images look weird on home page when chrome force-dark-mode flag is enabled

### ISSUE THREAD

**Issue by jalaj-k** [jalaj-k/praeco#12]
As is visible in this screenshot, the images on homescreen look weird, when dark mde is forced through chrome flag.

![Screenshot from 2020-08-20 00-04-04](https://user-images.githubusercontent.com/67556827/90676014-eab67380-e278-11ea-83f3-0fa48a14ca11.png)

I think using images with transparent background will fix this one.

**Comment by Prathamesh-B** [comment]
![image](https://user-images.githubusercontent.com/55992548/90729411-2fc3bf80-e2e4-11ea-8930-eecbceb382d1.png)

Fix
